import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { AuthSessionBootstrap } from '@auth';
import { QueryProvider, ToastProvider } from '@core';
import { StoreProvider } from '@store';
import { createSiteMetadata } from '@utils/seo';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const siteName = 'Create Next App';

export const metadata: Metadata = createSiteMetadata({
	siteName,
	description: 'Generated by create next app',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<StoreProvider>
					<QueryProvider>
						<AuthSessionBootstrap />
						<ToastProvider />
						{children}
					</QueryProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
